non-code activity log update
badging/eventBadging pull request #34
Opened 2022-10-12 17:55 UTC by oma131

Signed-off-by: oma131 <anosikeihuoma@gmail.com>

2022-10-17 19:37 UTC, Ruth-ikegah commented on NON-CODE_ACTIVITY-LOG.md
> +This file contains a table that shows all non-code contributions made in the CHAOSS Community.
Hey @oma131, please can you edit this to "The CHAOSS Badging Website"? Then also add instructions like; you can make a PR to this file adding your details to the table.

2022-10-17 19:38 UTC, Ruth-ikegah requested changes
Hey @oma131, thanks for putting this together. I dropped a comment.

2022-10-17 20:59 UTC, oma131 commented on NON-CODE_ACTIVITY-LOG.md
> +This file contains a table that shows all non-code contributions made in the CHAOSS Community.
Hello @Ruth-ikegah can you explain a bit more about the details I should add?

2022-10-17 21:50 UTC, Ruth-ikegah commented on NON-CODE_ACTIVITY-LOG.md
> +This file contains a table that shows all non-code contributions made in the CHAOSS Community.
Something along these lines: " We value and accept Non-code contributions, so we created a way for you to log in your contributions. This file contains a table that shows all non-code contributions made on the CHAOSS Badging Website.

To log in your contributions, make a Pull request to this file in the order below; thank you."

2022-10-19 04:31 UTC, oma131 commented on NON-CODE_ACTIVITY-LOG.md
> +This file contains a table that shows all non-code contributions made in the CHAOSS Community.
@Ruth-ikegah I have made the changes please review them

2022-10-19 11:19 UTC, Ruth-ikegah approved these changes
alright this looks great now!

2022-10-19 11:20 UTC, merged